Clarify what is meant by "personal data".
w3c/controller-document pull request #105
Opened 2024-10-12 21:54 UTC by msporny

This PR is an attempt to partially address issue #93 by adding a Use Cases and Requirements section.

2024-10-13 07:08 UTC, iherman approved these changes

2024-10-13 16:07 UTC, David-Chadwick approved these changes
Subject to minor editorial

2024-10-13 16:07 UTC, David-Chadwick commented on index.html
> +might include pseudonymous information, such as a public cryptographic key,
```suggestion
might include pseudonymous information, such as a public cryptographic key or an IP address, 
```

2024-10-13 18:22 UTC, dlongley approved these changes

2024-10-15 17:14 UTC, TallTed requested changes
Small stuff.

2024-10-15 17:14 UTC, TallTed commented on index.html
> +public-facing, it is <em>critical</em> that the [=controller document=] contains
```suggestion
public-facing, it is <em>critical</em> that [=controller documents=] contain
```

2024-10-15 17:14 UTC, TallTed commented on index.html
> +communication channels.
```suggestion
account in a [=controller document=]. A better alternative is to transmit
such personal data through other means such as verifiable credentials
[[?VC-DATA-MODEL-2.0]] or other data formats sent over private and secure
communication channels.
```

2024-10-19 20:56 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-10-19 20:56 UTC, merged