Specify that semantics are the same if @context is not used.
w3c/controller-document pull request #106
Opened 2024-10-13 14:49 UTC by msporny

This PR is an attempt to partially address issue #94 by specifying that document semantics are the same even when `@context` is not used.

/cc @jyasskin and @hadleybeeman

2024-10-13 14:50 UTC, iherman approved these changes

2024-10-13 14:53 UTC, longpd approved these changes

2024-10-13 16:24 UTC, David-Chadwick approved these changes

2024-10-13 16:24 UTC, David-Chadwick commented on index.html
> +value or JSON-LD processors are used or not, the semantics for all properties
```suggestion
value and/or JSON-LD processors are used or not, the semantics for all properties
```

2024-10-13 18:19 UTC, dlongley approved these changes

2024-10-15 15:58 UTC, TallTed requested changes

2024-10-15 15:58 UTC, TallTed commented on index.html
> +value or JSON-LD processors are used or not, the semantics for all properties
Includes @David-Chadwick's [tweak](https://github.com/w3c/controller-document/pull/106/files#r1798441716).
```suggestion
`@context` declaration at the top-level of the document. Whether or not the
`@context` value or JSON-LD processors are used, the semantics for all properties
```

2024-10-15 15:58 UTC, TallTed commented on index.html
> +value or JSON-LD processors are used or not, the semantics for all properties
Included in my suggestion below.

2024-10-16 16:07 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-10-16-vcwg#section4-2) on 2024-10-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Specify that semantics are the same if @context is not used. (pr controller-document#106)

_See github pull request [controller-document#106](https://github.com/w3c/controller-document/pull/106)._




**Manu Sporny:** the TAG said a JSON-LD processor might resolve to a different solution to pure JSON processing, so need to make clear that this is not the case.  
… so even if `@context` is not there, the result should still be the same.  
… if you get two different results then you have a bug in one of your processors.  

> *Ivan Herman:* +1 to put this into VCDM.

> *Phillip Long:* +1 to putting this in the VCDM for consistency.

</details>

2024-10-17 16:29 UTC, pchampin commented
This was discussed during the [did meeting on 17 October 2024](https://www.w3.org/2024/10/17-did-minutes.html#6826).

<details><summary><i>View the transcript</i></summary>

<h4><a href="https://github.com/w3c/did-core/issues/863" rel="noopener noreferrer">w3c/<wbr>did-core#863</a></h4>
<p><cite>manu:</cite> during TPAC, the TAG suggested to add some text in the VC documents about JSON-LD,<br>
<span>… but that also applies to the DID WG.</span><br>
<span>… The text is to explain (even more) clearly that downloading JSON-LD contexts from the web is not necessary for complying with the standard.</span><br>
<span>… And that processing a VC or DID document as JSON is equivalent to processing it as JSON-LD.</span><br>
<span>… The proposal was to add some text saying "any difference in the behaviour between JSON and JSON-LD would be a bug of this spec"</span><br>
<span>… We have some text to this effect in VC.</span><br>
<span>… In the Controller Document spec, we got to a point where there is no difference between JSON and JSON-LD processing.</span><br>
<span>… As a side effect, we can have a single media-type.</span></p>
<p><cite>&lt;ivan&gt;</cite> <a href="https://github.com/w3c/controller-document/pull/106" rel="noopener noreferrer">VC's version on the JSON(-LD) that Manu was talking about:</a></p>
<p><cite>manu:</cite> We never picked a media-type because of 5-year long debate at IETF about multiple suffixes in media-types.<br>
<span>… The proposal to this group is to do the same for did: would people be happy with a media-type like application/did ?</span><br>
<span>… We haven't heard any pushback so far. Should be take a resolution?</span></p>
<p><cite>markus_sabadello:</cite> A CBOR representation would have a different media type, but there would be no difference between JSON and JSON-LD?</p>
<p><cite>manu:</cite> correct</p>
<p><cite>markus_sabadello:</cite> I think that would be fine, sounds like a good idea, one thing I'm wondering, separate media type for DID Resolution result.</p>
<p><cite>markus_sabadello:</cite> Separate media type for that, I think that's fine, sounds like a separate question we can discuss separately, but don't think there would be any implications/problems, sounds good.</p>
<p><cite>manu:</cite> I agree, we should have a separate media-type for DID Resolution results.<br>
<span>… Another thing we did in VC is tell people "use the most accurate media-type when you serve these documents".</span><br>
<span>… Many people get media-types wrong, so often that people are encouraged to not rely on media-types.</span><br>
<span>… For a JSON(-LD) prepresentation, this would be application/did ; for a CBOR representation, this would be something like application/did+cbor .</span><br>
<span>… Serving a DID document as application/ld+json or application/json is not wrong, but not optimal.</span><br>
<span>… A text to this effect has reached consensus in the VC WG, I will do something similar for DID.</span><br>
<span>… Developers should be ready to deal with lower fidelity media-types.</span></p>
<p><cite>Wip:</cite> Quick comment, this text is in the controller document, will we rely on that? Controller document has its own media type?</p>
<p><cite>manu:</cite> good question. I think the Controller Document will have its own media-type.<br>
<span>… We don't want to duplicate content. I try to get a sense of what the group wants.</span><br>
<span>… We fist need a decision on the DID document media-type, then we can discuss the rest.</span></p>
<p><cite>Wip:</cite> Any comments on the draft proposals?</p>
<p><cite>pchampin:</cite> Without being too pedantic, the spec makes a clear disctinction between a DID and a DID Document, application/did might be a bit confusing since a DID is an identifier?</p>
<p><cite>manu:</cite> I take your point. I'm wondering if it matters all that much?</p>
<p><cite>&lt;ivan&gt;</cite> +1 manu</p>
<p><cite>manu:</cite> I don't think we would ever serve a pure DID with a media-type.<br>
<span>… It feels nicer to have a short compact media-type.</span></p>
<p>PROPOSAL: The media type for the JSON and JSON-LD expression of a DID Document will be application/did.</p>
<p><cite>&lt;dmitriz&gt;</cite> +1</p>
<p><cite>&lt;TallTed&gt;</cite> +1</p>
<p><cite>&lt;Wip&gt;</cite> +1</p>
<p><cite>&lt;manu&gt;</cite> +1</p>
<p><cite>&lt;ivan&gt;</cite> +1</p>
<p><cite>&lt;markus_sabadello&gt;</cite> +1</p>
<p><cite>&lt;pchampin&gt;</cite> +0.5</p>
<p><cite>&lt;JennieM&gt;</cite> +1</p>
<p><cite>&lt;bigbluehat&gt;</cite> +1</p>
<p><strong>RESOLUTION:</strong> The media type for the JSON and JSON-LD expression of a DID Document will be application/did.</p>
<p>PROPOSAL: The specification should warn that it is possible to use lower fidelity media types like application/json or application/ld+json to serve DID Documents and that implementations should be aware of this fact and use the highest precision media type in their applications.</p>
<p><cite>&lt;manu&gt;</cite> +1</p>
<p><cite>&lt;Wip&gt;</cite> +1</p>
<p><cite>&lt;dmitriz&gt;</cite> +1</p>
<p><cite>&lt;TallTed&gt;</cite> +1</p>
<p><cite>&lt;JennieM&gt;</cite> +1</p>
<p><cite>&lt;ivan&gt;</cite> +1</p>
<p><cite>&lt;JoeAndrieu&gt;</cite> +1</p>
<p><cite>&lt;markus_sabadello&gt;</cite> +1</p>
<p><cite>&lt;pchampin&gt;</cite> +1</p>
<p><strong>RESOLUTION:</strong> The specification should warn that it is possible to use lower fidelity media types like application/json or application/ld+json to serve DID Documents and that implementations should be aware of this fact and use the highest precision media type in their applications.</p>

<hr /></details>

2024-10-19 20:57 UTC, msporny commented
Substantive, multiple reviews, changes requested and made, no objections, merging.

2024-10-19 20:57 UTC, merged