Add section on integrity protection of remote controller documents.
w3c/controller-document pull request #108
Opened 2024-10-13 21:12 UTC by msporny

This PR is an attempt to partially address issue #94 by adding a security consideration section on integrity protection of remote controller documents.

/cc @jyasskin and @hadleybeeman

2024-10-14 07:49 UTC, iherman approved these changes

2024-10-15 18:01 UTC, TallTed requested changes

2024-10-15 18:01 UTC, TallTed commented on index.html
> +protection.
```suggestion
[[[VC-DATA-INTEGRITY]]] could be employed by a mechanism that can provide
such protection.
```

2024-10-16 15:04 UTC, dlongley approved these changes

2024-10-19 20:34 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-10-19 20:35 UTC, merged