Explain that references to external verification methods is allowed.
w3c/controller-document pull request #109
Opened 2024-10-14 01:07 UTC by msporny

This PR is an attempt to partially address issue #94 by explaining that eferences to external verification methods are allowed and dereferencing those values must be done using the algorithm in the specification.

/cc @jyasskin and @hadleybeeman

2024-10-14 07:51 UTC, iherman approved these changes

2024-10-15 18:11 UTC, TallTed requested changes

2024-10-15 18:11 UTC, TallTed commented on index.html
> +that is external to a [=controller document=] is a valid usage of this
```suggestion
that is external to a [=controller document=] is a valid use of this
```

2024-10-15 18:11 UTC, TallTed commented on index.html
> +without the consent (that is, without a bi-directional reference) of the victim.
```suggestion
used to confirm that the [=controller document=] refers to the
[=verification method=] (via a [=verification relationship=])
and that the [=verification method=] refers to the [=controller document=]
(via the [=verification method=]'s `controller` property). Failure to
confirm that these reciprocal relationships exist can lead to security
compromises where an attacker poisons a cache by claiming control of a
[=verification method=] without the consent (that is, without a reciprocal
reference) of the victim.
```

2024-10-19 16:54 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-10-19 16:54 UTC, merged