Editorial improvements resulting from review of 20240817 draft
w3c/controller-document pull request #71
Opened 2024-08-25 23:51 UTC by selfissued

These changes apply editorial improvements resulting from [my spec review](https://lists.w3.org/Archives/Public/public-vc-wg/2024Aug/0018.html).  Issues #46 through #70 were opened to facilitate working group discussion on more substantive issues resulting from the review.

2024-08-26 20:40 UTC, decentralgabe approved these changes

2024-08-29 14:53 UTC, msporny approved these changes
Approved with minor nits.

2024-08-30 02:48 UTC, selfissued commented on index.html
> +the JWK Thumbprint [[RFC7638]] using the SHA-256 hash function of the [=public key=].
RFC 7638, RFC 7517 (JWK), and the rest of the underlying specs all call it SHA-256.  It would be inconsistent to make this change.

2024-08-30 17:10 UTC, dlongley commented on index.html
> +specify how an entity can generate a content encryption key in order to transmit
I think this is a little too specific and might lead an implementer to think that they can't use key encapsulation or that some other hairy / overly prescriptive things might block them from using this for encryption when that's not intent here. I recommend this more general text:

```suggestion
specify how an entity can perform encryption in order to transmit
```

2024-08-30 19:11 UTC, dlongley approved these changes

2024-08-30 19:47 UTC, TallTed requested changes

2024-08-30 19:47 UTC, TallTed commented on index.html
>  as `DataIntegrityProof`, are used.
```suggestion
The `@context` property is used by implementations that employ JSON-LD to ensure that implementations are using the
same semantics when terms in this specification are processed. For example, this
can be important when properties like `type` are processed and its values, such
as `DataIntegrityProof`, are used.
```

2024-08-31 16:10 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-08-31 16:10 UTC, merged