Add Service feature based on W3C TPAC 2024 discussion.
w3c/controller-document pull request #99
Opened 2024-09-27 00:46 UTC by msporny

During the DID WG meeting at W3C TPAC, it was noted that the Controller Document specification doesn't include service descriptions and that is a mistake. This PR addresses the issue raised and ensures that services can be expressed on Controller Documents as they are expressed on DID Documents today, bringing the two document types in parity with one another.

2024-09-27 11:06 UTC, David-Chadwick approved these changes

2024-09-27 15:51 UTC, TallTed requested changes
These changes make the descriptions consistent with each other.

2024-09-27 15:51 UTC, TallTed commented on index.html
> +`service` entries with the same `id`.
```suggestion
The `id` property is OPTIONAL. If present, its value MUST be a URL
conforming to [[[URL]]]. A [=conforming document=] MUST NOT include multiple
`service` entries with the same `id`.
```

2024-09-27 15:51 UTC, TallTed commented on index.html
> +[[[?VC-EXTENSIONS]]].
```suggestion
The `type` property is REQUIRED. Its value MUST be a
<a data-cite="INFRA#string">string</a> or a
<a data-cite="INFRA#ordered-set">set</a> of
<a data-cite="INFRA#string">strings</a>. To maximize interoperability,
the [=service=] type and its associated properties SHOULD be registered in the
[[[?VC-EXTENSIONS]]].
```

2024-09-27 15:51 UTC, TallTed commented on index.html
> +values MUST be valid URLs conforming to [[[URL]]].
```suggestion
The `serviceEndpoint` property is REQUIRED. The value of the `serviceEndpoint`
property MUST be a single <a data-cite="INFRA#string">string</a>, a single
<a data-cite="INFRA#maps">map</a>, or a <a data-cite="INFRA#ordered-set">set</a>
composed of one or more
<a data-cite="INFRA#string">strings</a> and/or
<a data-cite="INFRA#maps">maps</a>. Each <a data-cite="INFRA#string">string</a>
value MUST be a valid URL conforming to [[[URL]]].
```

2024-09-27 18:02 UTC, iherman commented
Well... we may have a small problem. At the moment, the DID context file (https://www.w3.org/ns/did/v1) places the `service` property (and related properties) into its own vocabulary (as `https://www.w3.org/ns/did#service`). If the property moves into the controller document, the properties must be added to the security vocabulary, where all the controller terms live.

It is doable, of course, and it is relatively straightforward. But it affects the core DID context and specification... Actually, that namespace becomes moot...

2024-09-27 19:04 UTC, decentralgabe approved these changes

2024-09-27 19:13 UTC, selfissued approved these changes

2024-10-06 15:36 UTC, msporny commented
@iherman wrote:
> It is doable, of course, and it is relatively straightforward.

Yes, and we can take care of the updates/changes once we move things over.

> But it affects the core DID context and specification... Actually, that namespace becomes moot...

I don't think the namespace becomes moot, if so, that would be a backwards incompatible change. The good thing is that contexts can include vocabulary terms from any vocabulary, we'll have to do some re-shuffling, but it's largely administrative after we discuss the details w/ the WG.

2024-10-06 15:37 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-10-06 15:37 UTC, merged

2024-10-07 08:28 UTC, iherman commented
> @iherman wrote:
> 
> > It is doable, of course, and it is relatively straightforward.
> 
> Yes, and we can take care of the updates/changes once we move things over.
> 

I am not sure what your intention is here: should we add the services to the DI vocabulary?

If so...

> > But it affects the core DID context and specification... Actually, that namespace becomes moot...
> 
> I don't think the namespace becomes moot, if so, that would be a backwards incompatible change. The good thing is that contexts can include vocabulary terms from any vocabulary, we'll have to do some re-shuffling, but it's largely administrative after we discuss the details w/ the WG.

... this seems to be in contradiction. Or is it your intention that the 'services' term should _not_ added to the DI vocabulary after all, and it remains (the only) term in the DID vocabulary?

We can't have it both. (Well, technically, we could add a 'sameAs' statement somewhere, but that is not usually understood.)

At this point, I do not care about the context. The context does not define a vocabulary, just the mappings. But we will end up with the awkward situation (which was introduced by the DID spec back then) that all terms defined in the document are added to the DI vocabulary, _except_ for the service which is the only entry in the DID part. It is, though technically possible, awkward and unjustified...